### ISSUE TITLE
MacOS not loading from ~/.kube/config

### ISSUE THREAD

**Issue by IdiosApps** [kdash-rs/kdash#417]
**Describe the bug**
- Installed with Homebrew, 0.4.6
- `kdash` presents the application fine, but shows Error:
> Unable to obtain Kubernetes client. failed to infer config: in-cluster: (failed to read an incluster environment variable: environment variable not found), kubeconfig: (failed to determine currrent context)
Have to make my terminal tiny to see the whole error. After a few seconds, it changes to:
> channel closed
- Also tried with Exported `KUBE_CONFIG`, `KUBECONFIG`, `kubeconfig`, `KUBE_CONFIG_PATH` as `~/.kube/config` in ~/.zshrc, and ran `source ~/.zshrc`

On the other hand, `k9s` loads from `~/.kube/config` just fine.

I can't see documentation on what setup is required for MacOS.
I tried the Docker command, but get the same error. The only difference is that docker and docker-compose are now "Not found" in the CLI Info tab. 

**Expected behavior**
MacOS should load from ~/.kube/config by default

 
**Screenshots**

**Desktop (please complete the following information):**
 - macOS 14.2.1
 - iTerm, 3.4.23
 - zsh, 5.9
 - ? Kubectl Client Version [e.g. 1.19]
     - kubernetes-cli 1.29.0 
 - ? Kubectl Server Version [e.g. 1.19]
     - kubernetes-cli 1.29.0 
 - KDash version 0.4.6

Note: kubectl client, kubectl server are `Not found` from brew-installed kdash

**Comment by deepu105** [comment]
Hi, i'm having difficulty reproducing this, can you please share more info

Mac Architecture (M1 arm64 or Intel)

**Comment by IdiosApps** [comment]
@deepu105 M1 Pro

**Comment by deepu105** [comment]
Thats strange. I tried on an M1 mac and it works fine. Was kubectl also installed using brew?

**Comment by IdiosApps** [comment]
Yeah, tried brew and manual shell install too, same result.

Any other info I can give to help debug?

**Comment by deepu105** [comment]
Given you are seeing issues in all platforms I'm wondering if there is something to do with the way your environments are set up. I'm unfortunately unable to debug since I'm unable to reproduce this. Are you able to clone the repo and debug this in VsCode?

**Comment by deepu105** [comment]
I'm going to build a new feature allowing users to debug the app easily and provide the logs. #424 

Hopefully that will help to solve this issue

**Comment by IdiosApps** [comment]
> I'm going to build a new feature allowing users to debug the app easily and provide the logs. #424
> 
> Hopefully that will help to solve this issue

Thanks, I'll happily try that out. I can try and run with debug too, just need to find the time for it :)

**Comment by deepu105** [comment]
I pushed a version (0.6) with debug mode, can you tray and provide me the log `kdash -d=debug`

**Comment by IdiosApps** [comment]
Here is what I have seen with `--debug`, nice feature btw :) 

```
22:15:14 [INFO] Debug mode is enabled. Level: Info, KDash version: 0.6.0
22:15:14 [INFO] Starting network thread
22:15:14 [INFO] Starting cmd runner thread
22:15:14 [INFO] Starting network stream thread
22:15:14 [INFO] Starting UI
22:15:14 [INFO] env KUBECONFIG: Some("/Users/idiosapps/.kube/config")
22:15:14 [WARN] Getting kubernetes client by inference. No context given
22:15:14 [INFO] env KUBECONFIG: Some("/Users/idiosapps/.kube/config")
22:15:14 [WARN] Getting kubernetes client by inference. No context given
22:15:14 [INFO] Caching all resource data
22:15:14 [INFO] Cmd event received: GetCliInfo
22:15:14 [ERROR] Unable to obtain Kubernetes client. failed to infer config: in-cluster: (failed to read an incluster environment variable: environment variable not found), kubeconfig: (failed to determine current context)

Caused by:
    failed to determine current context
22:15:14 [ERROR] Unable to obtain Kubernetes client. failed to infer config: in-cluster: (failed to read an incluster environment variable: environment variable not found), kubeconfig: (failed to determine current context)

Caused by:
    failed to determine current context
22:15:19 [INFO] Input event received: KeyEvent { code: Char('c'), modifiers: KeyModifiers(CONTROL), kind: Press, state: KeyEventState(0x0) }
22:15:19 [INFO] Shutting down
```

Here is a snippet of my `$HOME/.kube/config`:

```
apiVersion: v1
clusters:
- cluster:
    server: https://my-kube-api.foo.bar
  name: my-kube-api
contexts:
- context:
    cluster: my-kube-api
    user: idiosapps
  name: my-kube-api
kind: Config
users:
- name: idiosapps
  user:
    token: my-token
```

Is there something I should run with kubectl to set the context/"in-cluster"?
I pretty much always use `k9s`, so I don't do `kubectl set-context my-kube-api` or whatever - the entry screen of k9s is choosing a context.
Looking at the [UI in the readme](https://github.com/kdash-rs/kdash/blob/main/screenshots/ui.gif), I don't see a Context tab - but I do see `All Contexts <C>`. I assumed it'd be similar behaviour to k9s - point the context, namespace, etc. inside k9s/kdash.

**Comment by deepu105** [comment]
I think it could be because of not having a default context. What happens if you set a context using kubectl and then try Kdash?

Also can you provide your full kube/config file after removing anything sensitive and private so I can try to reproduce? Coz i think it could be a problem parsing your config file

**Comment by IdiosApps** [comment]
`kubectl config set-context my-kube-api`
Still fails with the same error
```
Caused by:
    failed to determine current context
```

BUT good news! With:
`kubectl config use-context my-kube-api`
It sees the `kubectl client` & `kubectl server`, and lists all the pods, namespaces, contexts, etc.

---

Possible issue:
In the Contexts screen, I am pressing Enter on a blue context with the `=>` to show it's selected. But, my context isn't changing from the current yellow one.
Edit: It did, about 3 minutes later 🤔 

---

Possible improvement:
I changed the namespace to one I'm interested in, and the pods filtered correctly. But, I had to scroll down many namespaces to find it. Is there a way to text-filter? In `k9s` I can press `/` and then type what I want to find, which is super convenient.

--- 

Possible issue:
Also, it can be slow to filter the Resources (Pods). I can select a namespace and then it takes about a minute to filter down from thousands to single-digit pods. 

---

Possible improvement:
Pods -> Containers -> Logs seems to just tail. Is it possible to review last 5/10/15 minutes of logs?

---

I'm happy to split those into new issues, but they might be user error. Wanted to check here  first.

Really looking forward to a lighter & faster tool to interact with the clusters :) Thanks @deepu105!

**Comment by IdiosApps** [comment]
I have opened separate issues :) Thank you so much!
